### ISSUE TITLE
DPKG Error: package architecture (any) does not match system (amd64)

### ISSUE THREAD

**Issue by adrianaryaputra** [acedron/abstouch-nux#4]
i got the following message after trying to install this package with dpkg.
`
dpkg: error processing archive /home/ad/Downloads/Programs/abstouch-nux_1.3.0-1.
deb (--unpack):
 package architecture (any) does not match system (amd64)
`

any solution to solve this problem?

`
> dpkg --print-architecture
amd64

> dpkg --print-foreign-architectures
i386
`

**Comment by acedron** [comment]
@adrianaryaputra Can you try the following command and tell me the result?

```bash
dpkg --info "/home/ad/Downloads/Programs/abstouch-nux_1.3.0-1.deb" | awk '/Architecture/ {printf "arch:\t%s\n", $2}'
```

**Comment by acedron** [comment]
Release **[v1.3.0 Revise 2](https://github.com/acedron/abstouch-nux/releases/tag/v1.3.0)** should have fixed the issue. Can you try reinstalling it @adrianaryaputra?

**Comment by adrianaryaputra** [comment]
thanks, the installation is working now.. but i'm using Ubuntu 20.04 and can't obtain libc6 version 2.32 ... i'll try to build from source instead.

**Comment by acedron** [comment]
Thanks.

Closing as resolved.
